ALTER TABLE OffLineDisposicion	ADD COLUMN IdCliente			INTEGER NOT NULL DEFAULT 0;
ALTER TABLE OffLineDisposicion	ADD COLUMN IdClienteMoral		INTEGER NOT NULL DEFAULT 0;
ALTER TABLE OffLineDisposicion	ADD COLUMN IdGrupoSolidario		INTEGER NOT NULL DEFAULT 0;
ALTER TABLE OffLineCobranza		ADD COLUMN IdCliente			INTEGER NOT NULL DEFAULT 0;
ALTER TABLE OffLineCobranza		ADD COLUMN IdClienteMoral		INTEGER NOT NULL DEFAULT 0;
ALTER TABLE OffLineCobranza		ADD COLUMN IdGrupoSolidario		INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS IntegrantesGrupoOffline (
    Id						INTEGER PRIMARY KEY AUTOINCREMENT,
	IdRef					INTEGER NOT NULL DEFAULT 0,
	IdTipoRef				INTEGER NOT NULL DEFAULT 0,--1 Disposiciones, 2 - Cobranza, 3 - Pagos Prestamo
	IdPrestamo				INTEGER NOT NULL DEFAULT 0,
	IdGrupoSolidario		INTEGER NOT NULL DEFAULT 0,
	IdRelGrupoCliente		INTEGER NOT NULL DEFAULT 0,
    IdCliente				INTEGER NOT NULL DEFAULT 0,
	cNombre					TEXT NOT NULL DEFAULT '',
	nMonto					REAL NOT NULL DEFAULT 0,
	nGarantia				REAL NOT NULL DEFAULT 0,
	IdRol					INT DEFAULT 0,
	nMontoPago				REAL NOT NULL DEFAULT 0
);